// SEO Issue Categories and Keywords for GA4 Analysis

import s from "connect-redis";

// SEO Issue Categories and Keywords
export const SEO_INTENT_KEYWORDS: Array<string> = [
  "crawl",
  "crawl issue",
  "crawlability",
  "index",
  "indexing",
  "indexing issue",
  "indexability",
  "not indexed",
  "noindex",
  "nofollow",
  "robots",
  "robots.txt",
  "x-robots",
  "x-robots-tag",
  "meta robots",
  "http status",
  "status code",
  "response code",
  "4xx",
  "4xx error",
  "5xx",
  "5xx error",
  "redirect",
  "redirect chain",
  "redirect loop",
  "301",
  "302",
  "url",
  "urls",
  "url structure",
  "parameter",
  "parameter url",
  "pagination",
  "site architecture",
  "site hierarchy",
  "canonical",
  "canonical issue",
  "duplicate",
  "duplicate url",
  "on page seo",
  "title",
  "title tag",
  "page title",
  "meta title",
  "meta description",
  "missing title",
  "duplicate title",
  "title length",
  "meta description missing",
  "meta description duplicate",
  "h1",
  "h1 missing",
  "multiple h1",
  "h2",
  "h2 issue",
  "heading issue",
  "content",
  "content issue",
  "content length",
  "thin content",
  "low quality content",
  "duplicate content",
  "content optimization",
  "seo content",
  "content seo",
  "blog seo",
  "content gap",
  "content cannibalization",
  "missing content",
  "poor content structure",
  "keyword optimization",
  "keyword stuffing",
  "internal linking",
  "internal links",
  "internal link",
  "orphan",
  "orphan page",
  "broken internal link",
  "link structure",
  "link depth",
  "click depth",
  "crawl depth",
  "navigation issue",
  "breadcrumb issue",
  "external link",
  "external links",
  "outbound links",
  "broken external link",
  "nofollow link",
  "dofollow link",
  "link equity",
  "link juice",
  "backlink issue",
  "spam link",
  "page speed",
  "site speed",
  "slow page",
  "performance issue",
  "core web vitals",
  "lcp",
  "cls",
  "fid",
  "ttfb",
  "render blocking",
  "mobile speed",
  "desktop speed",
  "mobile seo",
  "mobile usability",
  "mobile friendly",
  "responsive issue",
  "viewport issue",
  "mobile indexing",
  "mobile first indexing",
  "touch elements",
  "font size issue",
  "image seo",
  "image optimization",
  "missing alt text",
  "alt attribute",
  "large images",
  "image compression",
  "broken image",
  "image indexing",
  "structured data",
  "schema",
  "schema markup",
  "json ld",
  "json-ld",
  "schema error",
  "schema warning",
  "rich result",
  "rich snippet",
  "faq schema",
  "breadcrumb schema",
  "product schema",
  "validation error",
  "sitemap",
  "xml",
  "xml sitemap",
  "sitemap issue",
  "missing sitemap",
  "invalid sitemap",
  "search console",
  "gsc issue",
  "coverage issue",
  "excluded pages",
  "indexed not submitted",
  "submitted not indexed",
  "security issue",
  "https",
  "http",
  "https issue",
  "http to https",
  "ssl",
  "ssl issue",
  "mixed content",
  "unsafe content",
  "security warning",
  "seo",
  "technical seo",
  "seo audit",
  "seo health",
  "site health",
  "seo report",
  "website seo",
  "overall seo",
  "seo performance",
  "seo score",
  "seo analysis",
  "site audit",
  "screaming frog",
  "filter",
  "longer than",
  "shorter than",
  "missing",
  "group",
  "count",
  "overview",
  "list",
  "show",
  "screaming frog",
  "meta description",
  "redirect",
  "status code",
];
//GA4 SEO INTENT KEYWORDS ARRAY
export const GA4_INTENT_KEYWORDS: Array<string> = [
  "ga4",
  "google analytics 4",
  "ga4 setup",
  "ga4 configuration",
  "ga4 install",
  "ga4 integration",
  "ga4 not working",
  "ga4 issue",
  "ga4 report",
  "ga4 property",
  "ga4 property id",
  "measurement id",
  "measurement issue",
  "event",
  "events",
  "ga4 events",
  "custom event",
  "event tracking",
  "event parameters",
  "event name",
  "event count",
  "event not firing",
  "event missing",
  "auto events",
  "recommended events",
  "conversion",
  "conversions",
  "ga4 conversion",
  "mark as conversion",
  "conversion event",
  "conversion tracking",
  "key event",
  "ecommerce",
  "purchase",
  "revenue",
  "transaction",
  "add to cart",
  "checkout",
  "item view",
  "product performance",
  "sales",
  "monetization",
  "active users",
  "new users",
  "returning users",
  "traffic",
  "source",
  "medium",
  "channel",
  "traffic source",
  "acquisition",
  "user acquisition",
  "traffic acquisition",
  "engagement",
  "engagement rate",
  "engaged session",
  "average engagement time",
  "bounce rate",
  "session duration",
  "scroll",
  "click",
  "interaction",
  "user engagement",
  "funnel",
  "funnel analysis",
  "path exploration",
  "user journey",
  "conversion path",
  "drop off",
  "flow",
  "behavior flow",
  "navigation path",
  "data missing",
  "no data",
  "real time not working",
  "debug view",
  "tag not firing",
  "tracking issue",
  "data discrepancy",
  "data accuracy",
  "gtm",
  "google tag manager",
  "analytics report",
  "dashboard",
  "custom report",
  "exploration",
  "explore",
  "data analysis",
  "metrics",
  "dimensions",
  "last 7 days",
  "last 30 days",
  "last 90 days",
  "daily breakdown",
   "metrics breakdown",
  "monthly",  
   "time series",
  "trend",
   "sessions",
  "users",
  "top",
  "days"
];

export const GA4_HARD_SIGNALS:Array<string> = [
  "daily breakdown",
  "metrics breakdown",
  "last days",
  "last k days",
  "last 30 days",
  "days",
  "weekly",
  "monthly",
  "historical",
  "time series",
  "trend",
  "compare",
  "increase",
  "decrease",
  "average",
  "analytics",
  "ga4",
  "google analytics",
  "sessions",
  "users",
];
export const SEO_HARD_SIGNALS:Array<string>= [
  "screaming frog",
  "url",
  "urls",
  "http",
  "https",
  "title tag",
  "meta description",
  "indexability",
  "crawl",
  "canonical",
  "redirect",
  "status code",
  "4xx",
  "5xx",
  "noindex",
];
export const EXPLICIT_MIXED_SIGNALS:Array<string> = [
  "analytics and seo",
  "technical seo and analytics",
  "impact",
  "correlate",
  "relationship",
  "compare",
  "analysis",
  "explain",
  "why",
  "how",
  "effect",
  "influence",
  "trend",

];


